# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this build is to build and test on both Windows and Linux.

name: Build And Test

on:
  workflow_dispatch:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        framework: [net5.0]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: restore
      run: dotnet restore ./TestProject.sln

    - name: Build
      run: dotnet build ./TestProject.sln

    - name: Test
      id: test1
      run: dotnet test ./TestProject1.sln --framework ${{ matrix.framework }} --logger:"console;verbosity=detailed"
