# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this build is to build and test on both Windows and Linux.

name: Build And Test

on:
  workflow_dispatch:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}
    
    env:
      SOLUTION: ./TestProject.sln

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: [net5.0, net6.0]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
       
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: restore
      run: dotnet restore ${{ env.SOLUTION }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION }}

    - name: Test
      id: test1
      continue-on-error: true
      run: dotnet test ${{ env.SOLUTION }} --framework ${{ matrix.framework }} --logger:"console;verbosity=detailed" --logger:"trx;logfilename=${{ github.workspace }}/testResults.trx"

    - name: Retry tests
      if: steps.test1.outcome=='failure'
      run: pwsh -f ./retrytests.ps1 -TestResultFile ${{ github.workspace }}/testResults.trx -WorkingDirectory ${{ github.workspace }}
      